<?php
/**
 *
 * @author  R. Dale Owen   @mediotype
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<script type="text/javascript"><!--
    //<![CDATA[
    $$('#co-billing-form button.button').each(function(item){
        /*
        item.originonclick = item.onclick;
        item.onclick = function() {
            ga('ec:setAction', 'checkout', {
                'step': 2,
                'option': $('billing:postcode').value
            });
            item.onclick = item.originonclick;
            ga('send', 'event', 'Checkout', 'Option','Billing',{
                'hitCallback': function() {
                    item.click(item.originonclick);
                }
            });
        }
        */
    });
    //]]>-->
</script>