<?php
/**
 *
 * @author  R. Dale Owen   @mediotype
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<script type="text/javascript">
    //<![CDATA[
    //traditional magento checkout is billing, shipping, shipping options, payment
    $$('#co-shipping-method-form .button').each(function(item){
        /*
        item.originonclick = item.onclick;
        item.onclick = function() {
            var shipOptions = $$('#co-shipping-method-form input[name=shipping_method]');
            var shipOption = undefined;
            shipOptions.each(function(method){
                if(method.checked) {
                    shipOption = method;
                }
            });
            if(shipOption != undefined)
            {
                ga('ec:setAction', 'checkout', {
                    'step': 4,
                    'option': shipOption.value
                });
                ga('send', 'event', 'Checkout', 'Option', 'Shipping Method',{
                    'hitCallback': function() {
                        item.click(item.originonclick);
                    }
                });
            }
            item.onclick = item.originonclick;
        }
        */
    });
    //]]>
</script>