<?php

?>

<script type="text/javascript">
<?php $newsman_id =  Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>

var endpoint = "https://retargeting.newsmanapp.com";
var _nzmPluginInfo = '1:Magento1.x';
var _nzm = _nzm || [];
var _nzm_config = _nzm_config || [];
_nzm_config['disable_datalayer'] = 1;
_nzm_tracking_server = endpoint;
(function() {

    var a, methods, i;
    a = function(f) {
        return function() {
            _nzm.push([f].concat(Array.prototype.slice.call(arguments, 0)));
        }
    };
    methods = ['identify', 'track', 'run'];
    for (i = 0; i < methods.length; i++) {
        _nzm[methods[i]] = a(methods[i])
    };
    s = document.getElementsByTagName('script')[0];
    var script_dom = document.createElement('script');
    script_dom.async = true;
    script_dom.id = 'nzm-tracker';
    script_dom.setAttribute('data-site-id', '<?php echo $newsman_id ?>');
    script_dom.src = endpoint + '/js/retargeting/track.js';
    s.parentNode.insertBefore(script_dom, s);
})();

_nzm.run('require', 'ec');

var isProd = false;
let lastCart = sessionStorage.getItem('lastCart');
if (lastCart === null)
    lastCart = {};
let lastCartFlag = false;
let bufferedClick = false;
let firstLoad = true;
NewsmanAutoEvents();
setInterval(NewsmanAutoEvents, 5000);
BufferClick();

function NewsmanAutoEvents() {
    var ajaxurl = '/newsmanfetch.php?newsman=getCart.json';
    if (bufferedClick || firstLoad) {
        jQuery.post(ajaxurl, {
            post: true,
        }, function(response) {
            lastCart = JSON.parse(sessionStorage.getItem('lastCart'));
            if (lastCart === null)
                lastCart = {};
            //check cache
            if (lastCart.length > 0 && lastCart != null && lastCart != undefined && response.length > 0 &&
                response != null && response != undefined) {
                if (JSON.stringify(lastCart) === JSON.stringify(response)) {
                    if (!isProd)
                        console.log('newsman remarketing: cache loaded, cart is unchanged');
                    lastCartFlag = true;
                } else {
                    lastCartFlag = false;
                }
            }
            if (response.length > 0 && lastCartFlag == false) {
                _nzm.run('ec:setAction', 'clear_cart');
                _nzm.run('send', 'event', 'detail view', 'click', 'clearCart');
                for (var item in response) {
                    _nzm.run('ec:addProduct',
                        response[item]
                    );
                }

                _nzm.run('ec:setAction', 'add');
                _nzm.run('send', 'event', 'UX', 'click', 'add to cart');
                sessionStorage.setItem('lastCart', JSON.stringify(response));
                if (!isProd)
                    console.log('newsman remarketing: cart sent');
            } else {
                if (!isProd)
                    console.log('newsman remarketing: request not sent');
            }
            firstLoad = false;
            bufferedClick = false;

        });
    }
}

function BufferClick() {
    window.onclick = function(e) {
        const origin = ['a', 'input', 'span', 'i', 'button'];

        var click = e.target.localName;
        if (!isProd)
            console.log('newsman remarketing element clicked: ' + click);
        for (const element of origin) {
            if (click == element)
                bufferedClick = true;
        }
    }
}
</script>