<?php

$productCollection = $this->getLoadedProductCollection();
$helper = $this->helper('catalog/output');
$current_category = Mage::registry('current_category');
?>
<?php if (!$productCollection->count()): ?>
	<?php //no products were viewed ?>

<script type="text/javascript">
 <?php $newsman_id = Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>
</script>
	
<?php else: ?>
	<?php //create impression objects for all the products ?>
	<script type="text/javascript">

		//<![CDATA[

        <?php $newsman_id = Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>		

		<?php $position = 0 ?>
		<?php foreach ($productCollection as $product): ?>
		<?php //create php standard class convert to json string ?>
		<?php
		
		$impressionData = array(
			"id" => $product->getId(),
			"name" => $product->getName(),
			"position" => ++$position

		);

		if ($product->getManufacturer())
		{
			$impressionData['brand'] = $product->getManufacturer();
		}

		if (isset($current_category))
		{
			$impressionData['category'] = $current_category->getName();
			$impressionData['list'] = "Category View";

		} else
		{
			$impressionData['list'] = "Search Results";
		}

		?>

		_nzm.run('ec:addImpression', <?php echo json_encode($impressionData)?>);
		<?php endforeach; ?>

		_nzm.run('send', 'pageview');
		//]]>
	</script>
<?php endif; ?>