<?php

$product = $this->getCurrentProduct();
$current_category = Mage::registry('current_category');
$type = $product->getTypeId();
?>
<script type="text/javascript">    

    <?php $newsman_id = Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id');?>    

    //<![CDATA[

    <?php
$impressionData = array(
    "id" => $product->getId(),
    "name" => $product->getName(),
    "price" => $product->getPrice(),
);
if ($product->getManufacturer()) {
    $impressionData['brand'] = $product->getManufacturer();
}
if (isset($current_category)) {
    $impressionData['category'] = $current_category->getName();

}
?>

    var _isUpdate = false;
    var action = jQuery('#product_addtocart_form').attr('action');
    if (action.indexOf("updateItemOptions") >= 0){
        _isUpdate = true;
    }

    _nzm.run('ec:addProduct', <?php echo json_encode($impressionData) ?>);
    _nzm.run('ec:setAction', 'detail');

    _nzm.run('send', 'pageview');

</script>
