<?php

$items = $this->getItems();
$current_category = Mage::registry('current_category');
?>
<?php if($this->getItems()->getSize()): ?>
    <script type="text/javascript">
        //<![CDATA[

        <?php $newsman_id =  Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>	

        <?php $position = 0 ?>
        <?php foreach($items as $item): ?>
        <?php
            $impressionData = array(
                "id" => $item->getId(),
                "name" => $item->getName(),
                "position" => ++$position
                );
            if(isset($current_category)){
                $impressionData['category'] = $current_category->getName();

            }
            $impressionData['list'] = "Related Products";
        ?>
        _nzm.run('ec:addImpression', <?php echo json_encode($impressionData) ?>);
        //add click analysis to the links
        var rLinks = $$('#block-related > li:nth-child(<?php echo $position ?>) a');
        /*
        rLinks.each(function(link){
            link.onclick = function() {
                <?php unset($impressionData['list']) ?>
                _nzm.run('ec:addProduct', <?php echo json_encode($impressionData) ?>);
                _nzm.run( 'ec:setAction', 'add' );
                _nzm.run('send', 'event', 'UX', 'click', 'add to cart');
            };
        });
        */

        <?php endforeach; ?>

        _nzm.run('send', 'pageview');

        //]]>
    </script>
<?php endif; ?>
