<?php

$items = $this->getItems();
$current_category = Mage::registry('current_category');
?>
<?php if($this->getItems()->getSize()): ?>
    <script type="text/javascript">
        //<![CDATA[

        <?php $newsman_id =  Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>


        var endpoint = "https://retargeting.newsmanapp.com";
        var _nzm = _nzm || [];
        var _nzm_config = _nzm_config || [];
        _nzm_tracking_server = endpoint;
        (function () {
            var a, methods, i;
            a = function (f) {
                return function () {
                    _nzm.push([f].concat(Array.prototype.slice.call(arguments, 0)));
                }
            };
            methods = ['identify', 'track', 'run'];
            for (i = 0; i < methods.length; i++) {
                _nzm[methods[i]] = a(methods[i])
            }
            ;
            s = document.getElementsByTagName('script')[0];
            var script_dom = document.createElement('script');
            script_dom.async = true;
            script_dom.id = 'nzm-tracker';
            script_dom.setAttribute('data-site-id', '<?php echo $newsman_id ?>');
            script_dom.src = endpoint + '/js/retargeting/track.js';
            s.parentNode.insertBefore(script_dom, s);
        })();

        _nzm.run('require', 'ec');

        <?php $position = 0 ?>
        <?php foreach($items as $item): ?>
        <?php
            $impressionData = array(
                "id" => $item->getId(),
                "name" => $item->getName(),
                "position" => ++$position
                );
            if(isset($current_category)){
                $impressionData['category'] = $current_category->getName();

            }
            $impressionData['list'] = "Related Products";
        ?>
        _nzm.run('ec:addImpression', <?php echo json_encode($impressionData) ?>);
        //add click analysis to the links
        var rLinks = $$('#block-related > li:nth-child(<?php echo $position ?>) a');
        rLinks.each(function(link){
            link.onclick = function() {
                <?php unset($impressionData['list']) ?>
                _nzm.run('ec:addProduct', <?php echo json_encode($impressionData) ?>);
                _nzm.run( 'ec:setAction', 'add' );
                _nzm.run('send', 'event', 'UX', 'click', 'add to cart');
            };
        });

        <?php endforeach; ?>

        _nzm.run('send', 'pageview');

        //]]>
    </script>
<?php endif; ?>
