<?php

$items = $this->getItems();
$current_category = Mage::registry('current_category');
?>

<!--

<?php if(count($this->getItemCollection()->getItems())): ?>
    <script type="text/javascript">
        //<![CDATA[
        <?php $position = 0 ?>
        <?php $this->resetItemsIterator() ?>
        <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($item=$this->getIterableItem()): ?>
                <?php
                    $impressionData = array(
                        "id" => $item->getId(),
                        "name" => $item->getName(),
                        "position" => ++$position
                        );
                    if(isset($current_category)){
                        $impressionData['category'] = $current_category->getName();

                    }
                    $impressionData['list'] = "Upsell Products";
                ?>
                <?php endif; ?>
            <?php endfor; ?>
        <?php endfor; ?>
        //]]>        
    </script>
<?php endif; ?>

-->