<?php
/**
 * Sends product view data to Google Enhanced Ecommerce Analytics
 *
 * @author  Dale Owen @mediotype
 * @reference   https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce
 * @var $this Mage_Catalog_Block_Product_List_Upsell
 */
$items = $this->getItems();
$current_category = Mage::registry('current_category');
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
    <script type="text/javascript">
        //<![CDATA[
        <?php $position = 0 ?>
        <?php $this->resetItemsIterator() ?>
        <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($item=$this->getIterableItem()): ?>
                <?php
                    $impressionData = array(
                        "id" => $item->getId(),
                        "name" => $item->getName(),
                        "position" => ++$position
                        );
                    if(isset($current_category)){
                        $impressionData['category'] = $current_category->getName();

                    }
                    $impressionData['list'] = "Upsell Products";
                ?>
                ga('ec:addImpression', <?php echo json_encode($impressionData) ?>);
                //add click analysis to the links
                var uLinks = $$('#upsell-product-table tr:nth-child(<?php echo $_i + 1 ?>) td:nth-child(<?php echo $_j + 1 ?>) a');
                uLinks.each(function(link){
                    link.onclick = function() {
                        console.log('click worked');
                        <?php unset($impressionData['list']) ?>
                        ga('ec:addProduct', <?php echo json_encode($impressionData) ?>);
                        ga('ec:setAction', 'click',{list: 'Upsell Products'});
                        ga('send', 'event', 'UX', 'click', 'Upsell Products',{
                            'hitCallback': function() {
                                document.location = link.href;
                            }
                        });
                    };
                });
                <?php endif; ?>
            <?php endfor; ?>
        <?php endfor; ?>
        //]]>
    </script>
<?php endif; ?>
