<?php

/** @var $order Mage_Sales_Model_Order */
$order = $this->getOrder();
$totals = $this->getTotals();
?>
<script type="text/javascript">

<?php $newsman_id = Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>

    <?php foreach($order->getItemsCollection() as $item): ?>
    <?php /** @var $item Mage_Sales_Model_Order_Item */
          /** @var $product Mage_Catalog_Model_Product */ ?>
    <?php $product = Mage::getModel('catalog/product')->load($item->getProductId()); ?>
    <?php
        $impressionData = array(
            "id" => $product->getId(),
            "name" => $product->getName(),
            "price" => $item->getPrice(),
            "quantity" => $item->getQtyOrdered()
            );
        if($product->getManufacturer()){
            $impressionData['brand'] =$product->getManufacturer();
        }
        if($order->getDiscountDescription()){
            $impressionData['coupon'] =$order->getDiscountDescription();
        }
    ?>
    //ga('ec:addProduct', <?php echo json_encode($impressionData) ?>);
    <?php endforeach; ?>
    <?php
        $actionData = array(
            "id" => $order->getIncrementId(),
            "affiliation" => Mage::app()->getStore()->getName(),
            "revenue" => $totals->getAmount(),
            "tax" => $totals->getTax(),
            "shipping" => $totals->getShipping()
            );
        if($order->getDiscountDescription()){
            $actionData['coupon'] = $order->getDiscountDescription();
        }

        $e = $order->getShippingAddress()->getEmail();
        $f = $order->getShippingAddress()->getFirstname();
        $l = $order->getShippingAddress()->getLastname();
    ?>

    _nzm.identify({ email: "<?php echo $e; ?>", first_name: "<?php echo $f; ?>", last_name: "<?php echo $l; ?>" });

    _nzm.run('ec:setAction', 'purchase', <?php echo json_encode($actionData) ?>);
    _nzm.run('send', 'pageview');

</script>
