<?php

/** @var $order Mage_Sales_Model_Order */
$order = $this->getOrder();
$totals = $this->getTotals();
?>
<script type="text/javascript">

<?php $newsman_id = Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>

if(_nzm == undefined)
{
var endpoint = "https://retargeting.newsmanapp.com";
var _nzmPluginInfo = '1:Magento1.x';
var _nzm = _nzm || [];
var _nzm_config = _nzm_config || [];
_nzm_config['disable_datalayer'] = 1;
_nzm_tracking_server = endpoint;
(function () {

    var a, methods, i;
    a = function (f) {
        return function () {
            _nzm.push([f].concat(Array.prototype.slice.call(arguments, 0)));
        }
    };
    methods = ['identify', 'track', 'run'];
    for (i = 0; i < methods.length; i++) {
        _nzm[methods[i]] = a(methods[i])
    }
    ;
    s = document.getElementsByTagName('script')[0];
    var script_dom = document.createElement('script');
    script_dom.async = true;
    script_dom.id = 'nzm-tracker';
    script_dom.setAttribute('data-site-id', '<?php echo $newsman_id ?>');
    script_dom.src = endpoint + '/js/retargeting/track.js';
    s.parentNode.insertBefore(script_dom, s);
})();

_nzm.run('require', 'ec');
}

    <?php foreach($order->getItemsCollection() as $item): ?>
    <?php /** @var $item Mage_Sales_Model_Order_Item */
          /** @var $product Mage_Catalog_Model_Product */ ?>
    <?php $product = Mage::getModel('catalog/product')->load($item->getProductId()); ?>
    <?php
        $impressionData = array(
            "id" => $product->getId(),
            "name" => $product->getName(),
            "price" => $item->getPrice(),
            "quantity" => $item->getQtyOrdered()
            );
        if($product->getManufacturer()){
            $impressionData['brand'] =$product->getManufacturer();
        }
        if($order->getDiscountDescription()){
            $impressionData['coupon'] =$order->getDiscountDescription();
        }
    ?>
    //ga('ec:addProduct', <?php echo json_encode($impressionData) ?>);
    <?php endforeach; ?>
    <?php
        $actionData = array(
            "id" => $order->getIncrementId(),
            "affiliation" => Mage::app()->getStore()->getName(),
            "revenue" => $totals->getAmount(),
            "tax" => $totals->getTax(),
            "shipping" => $totals->getShipping()
            );
        if($order->getDiscountDescription()){
            $actionData['coupon'] = $order->getDiscountDescription();
        }

        $e = $order->getShippingAddress()->getEmail();
        $f = $order->getShippingAddress()->getFirstname();
        $l = $order->getShippingAddress()->getLastname();
    ?>

    _nzm.identify({ email: "<?php echo $e; ?>", first_name: "<?php echo $f; ?>", last_name: "<?php echo $l; ?>" });

    _nzm.run('ec:setAction', 'purchase', <?php echo json_encode($actionData) ?>);
    _nzm.run('send', 'pageview');

</script>
