<?php

$loggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
?>
<script type="text/javascript">
/*

    //<![CDATA[

    <?php $newsman_id =  Mage::getStoreConfig('mediotype_ee/mediotype_ee_settings/account_id'); ?>

<?php foreach($this->getItems() as $item): ?>
    <?php $product = $item->getProduct() ?>
    <?php
            $impressionData = array(
                "id" => $product->getId(),
                "name" => $product->getName(),
                "price" => $item->getPrice(),
                "quantity" => $item->getQty()
                );
            if($product->getManufacturer()){
                $impressionData['brand'] =$product->getManufacturer();
            }
        ?>
    _nzm.run('ec:addProduct', <?php echo json_encode($impressionData) ?>);
    _nzm.run('ec:setAction', 'checkout');
    _nzm.run('send', 'pageview');

<?php endforeach ?>

    //]]>

*/
</script>